package errs

func errcheck() error {
	fnWithError()

	return nil
}
